Update lite-tweaks-super

diff --git a/usr/bin/lite-tweaks-super b/usr/bin/lite-tweaks-super
--- a/usr/bin/lite-tweaks-super
+++ b/usr/bin/lite-tweaks-super
@@ -227,7 +227,6 @@ RCONFIG() {
         else
         zenity --info --width="300" --height="80" --title="  Lite Tweaks" --text="\nResidual configuration files have been cleared!"
     fi
-exit
 }
 
 FILES() {
@@ -418,46 +417,47 @@ return
 esac
 
 sed -i "s/^title=.*$/title=$title/;s/^black=.*$/black=$black/;s/white=.*$/white=$white/;s/^brown=.*$/brown=$brown/;s/^blue=.*$/blue=$blue/" /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth
-            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-                        echo "#Error"
-                    sleep 1
-                                        zenity --error \
-                                        --title="Error" --text="There was an error while\nFixing the bootup!\nUnable to write to /etc/lsb-release"
-                    return
-                        fi
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+        echo "#Error"
+        sleep 1
+        zenity --error \
+               --title="Error" --text="There was an error while\nFixing the bootup!\nUnable to write to /etc/lsb-release"
+        return
+    fi
 
 update-initramfs -u
-            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-                        echo "#Error"
-                    sleep 1
-                                        zenity --error \
-                                        --title="Error" --text="There was an error while\nFixing the bootup!\nStatus: update-initramfs fail."
-                    return
-                        fi
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+        echo "#Error"
+        sleep 1
+        zenity --error \
+               --title="Error" --text="There was an error while\nFixing the bootup!\nStatus: update-initramfs fail."
+        return
+    fi
 
 echo "Linux Lite $LL_VERSION LTS \n \l" | tee /etc/issue
-            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-                        echo "#Error"
-                    sleep 1
-                                        zenity --error \
-                                        --title="Error" --text="There was an error while\nFixing the bootup!\nUnable to write to /etc/issue"
-                    return
-                        fi
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+        echo "#Error"
+        sleep 1
+        zenity --error \
+               --title="Error" --text="There was an error while\nFixing the bootup!\nUnable to write to /etc/issue"
+        return
+    fi
 
 sed -i 's/^DISTRIB_DESCRIPTION=.*$/DISTRIB_DESCRIPTION="Linux Lite '"$LL_VERSION"'"/g' /etc/lsb-release
-            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-                        echo "#Error"
-                    sleep 1
-                                        zenity --error \
-                                        --title="Error" --text="There was an error while\nFixing the bootup!\nUnable to write to /etc/lsb-release"
-                    return
-                        fi
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+        echo "#Error"
+        sleep 1
+        zenity --error \
+               --title="Error" --text="There was an error while\nFixing the bootup!\nUnable to write to /etc/lsb-release"
+        return
+    fi
 }
 
 CLEARMEM() {
     echo "#Freeing up system memory, please standby..."
 sh -c 'echo 1 >/proc/sys/vm/drop_caches' && sh -c 'echo 2 >/proc/sys/vm/drop_caches' && sh -c 'echo 3 >/proc/sys/vm/drop_caches'
 sleep 2
+zenity --info --window-icon="$ic" --width="300" --height="80" --title="  Lite Tweaks" --text="\nTask freeing up system memory completed!"
 }
 
 FIXAPT() {
