add zRAM tweak
add zRAM tweak

diff --git a/usr/bin/lite-tweaks-super b/usr/bin/lite-tweaks-super
--- a/usr/bin/lite-tweaks-super
+++ b/usr/bin/lite-tweaks-super
@@ -84,6 +84,12 @@ if [ $? = 0 ];then
 ARRAYC+=('REMOVE')
 fi
 
+echo $FRM | grep "ZRAM" > /dev/null
+if [ $? = 0 ];then
+ARRAYC+=('ZRAM')
+fi
+
+
 # Call the zenity window icon.
 ic="/usr/share/icons/zenity-llcc.png"
 
@@ -618,8 +624,8 @@ PRELOAD() {
 
     # Preload Status Main dialog
     echo "#Configuring Preload..."
-    PRLOAD=$(zenity --list --imagelist --width="365" --height=230 --cancel-label="Quit" --ok-label="Change Status" --window-icon=$ic --title="$APPNAME" \
-              --text='                          <span font="Sans Bold 10">Preload Apps Status</span>\n\n    • <span font="Sans 9">Preload service is always started during boot up</span>' \
+    PRLOAD=$(zenity --list --imagelist --width="365" --height=232 --cancel-label="Quit" --ok-label="Change Status" --window-icon=$ic --title="$APPNAME" \
+              --text='                          <span font="Sans Bold 11">Preload Apps Status</span>\n\n    • <span font="Sans 9">Preload service is always started during boot up</span>' \
               --print-column=2 --column="  " --column="Preload" --column="Description" \
               $appicon1 "Running" "Preload service is currently running" \
               $appicon2 "Stopped" "Preload service is currently stopped" \
@@ -792,6 +798,109 @@ elif [[ $answ -eq "30" ]]; then
     exit 0
 fi
 done
+}
+
+ZRAM() {
+    echo "#Getting zRAM status. Please wait..." && sleep 1
+    APPNAME="   Lite Tweaks - zRAM"
+    SERVICE="zram-config"
+    LITEAPPSICONS=/usr/share/liteappsicons/litetweaks
+    appicon3=/usr/share/liteappsicons/litesoftware/ll-remove-software_32x32.png
+    # the loop
+    while (true); do
+    echo "#Configuring zRAM..."
+    # Is zram installed?
+    if [ -z  "$(dpkg -l | grep -E '^ii' | grep zram-config)" ]; then
+        # if not installed, then prompt user for installation
+        zenity --question --width="300" --height="80" --title="    $APPNAME" \
+               --text="\nzRAM is currently not enabled in your system.\n Would you like to enable zRAM support now?"
+               answer=$?
+        # Check Internet access
+        if eval "curl -sk google.com" >> /dev/null 2>&1; then
+            : # pass
+            else # Prompt ERROR internet connection
+            (zenity --question --icon-name=info --width="470" --height="90" --ok-label="Continue" --cancel-label="Cancel" --title="Lite Tweaks - No Internet connection detected" \
+                    --text="\n<b>Your computer doesn't seem to be connected to the Internet</b> \n \nLite Tweaks will attempt to install zRAM package from the local cache if available. \
+If the package does not exist in your system cache, zRAM installation will fail. \n\nYou can always check your Internet connection and try again at a later time.")
+            cacheinst=$?
+        fi
+                if [ "$cacheinst" -eq "0" ]; then
+                    echo "#Installing zRAM. Please wait..." && sleep 1
+                    apt-get install zram-config -y # install zram
+                    if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error..." && sleep 1
+                        zenity --error --width="260" --height="80" --title="    Error" \
+                               --text="\nAn error occurred while installing zRAM!"
+                        return
+                    else
+                        echo "#✔ zRAM successfully installed..." && sleep 1
+                        systemctl start zram-config
+                        continue
+                    fi
+                else # when user refuses installation, exit out zRAM Tweak
+                      exit 1
+                fi
+    fi
+    # check if zRAM service is running and assign variables
+    if [ -e /dev/zram0 ]; then
+        appicon1=$LITEAPPSICONS/appicon1-on.png
+        appicon2=$LITEAPPSICONS/appicon3-off.png
+    else
+        appicon1=$LITEAPPSICONS/appicon1-off.png
+        appicon2=$LITEAPPSICONS/appicon3-on.png
+    fi
+
+    # zRAM Status Main dialog
+    echo "#Configuring zRAM..."
+    sZRAM=$(zenity --list --imagelist --width="365" --height=232 --cancel-label="Quit" --ok-label="Change Status" --window-icon=$ic --title="$APPNAME" \
+              --text='                          <span font="Sans Bold 11">      zRAM Status</span>\n\n         • <span font="Sans 9">zRAM service is always started during boot up</span>' \
+              --print-column=2 --column="  " --column="zRAM" --column="Description" \
+              $appicon1 "Running" "zRAM service is currently running" \
+              $appicon2 "Stopped" "zRAM service is currently stopped" \
+              $appicon3 "Remove" "Stop service and Uninstall zRAM")
+
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+        return
+    fi
+
+    if [[ $sZRAM =~ Running ]]; then # Start
+            if [ -e /dev/zram0 ]; then
+                echo "#• zRAM is already running. No changes needed..." && sleep 2
+                continue
+            else
+                echo "#Starting zRAM..." && sleep 1
+                service zram-config start
+                echo "#✔ zRAM has been started" && sleep 1
+                continue
+            fi
+    elif [[ $sZRAM =~ Stopped ]]; then # Stop
+            if [ -e /dev/zram0 ]; then
+                echo "#Stopping zRAM..." && sleep 1
+                service zram-config stop
+                echo "#✔ zRAM has been stopped" && sleep 1
+            else
+                echo "#• zRAM is not running. No changes needed..." && sleep 2
+                continue
+            fi
+    elif [[ $sZRAM =~ Remove ]]; then # Remove Preload
+        zenity --question --width="265" --title="$APPNAME" --text="\nAre you sure you want to remove zRAM?"
+        if [ "$?" -eq "0" ]; then
+            echo "#Removing zRAM. Please wait..."
+            service zram-config stop && apt-get remove zram-config -y
+                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                    echo "#Error..." && sleep 1
+                    zenity --error --width="260" --height="80" --title="    Error" \
+                           --text="\nAn error occurred while removing zRAM!"
+                    return
+                else
+                    echo "#✔ zRAM successfully removed" && sleep 2
+                    return
+                fi
+        fi
+    else
+        zenity  --info --height="40" --title=" $APPNAME" --text="\nYou did not select an option. Please try again."
+    fi
+    done
 }
 
 ## Arrays execution
