updated numlock, preload, manage save session
Numlock
- removed unnecessary dialogs
- add status checks before writing settings
Preload
- add status checks before writing settings
Manage Save Session
- add status checks before writing settings

diff --git a/usr/bin/lite-tweaks-super b/usr/bin/lite-tweaks-super
--- a/usr/bin/lite-tweaks-super
+++ b/usr/bin/lite-tweaks-super
@@ -551,18 +551,16 @@ NUMLOCK() {
     # enable numlock
     if [[ "$EDNL" =~ "Enable" ]]; then
         if grep -q "numlockx on" /etc/lightdm/lightdm.conf; then
-            zenity --info --width="300" --height="60" --timeout=3 --height="60" --ok-label="Got it!" \
-                   --title=" Numlock" --text="\nNumlock at login is already enabled. No changes needed."
+            echo "#• Numlock is already enabled. No changes needed..." && sleep 2
         else
-            sed -i "s/numlockx off/numlockx on/g" /etc/lightdm/lightdm.conf && echo "#✔ Enabling Numlock at login..." && sleep .5
+            sed -i "s/numlockx off/numlockx on/g" /etc/lightdm/lightdm.conf && echo "#✔ Enabling Numlock at login..." && sleep 1
         fi
     # disable numlock
     elif [[ "$EDNL" =~ "Disable" ]]; then
         if grep -q "numlockx off" /etc/lightdm/lightdm.conf; then
-            zenity --info --width="300" --height="60" --timeout=3 --height="60" --ok-label="Got it!" \
-                   --title=" Numlock" --text="\nNumlock at login is already disabled. No changes needed."
+            echo "#• Numlock is already disabled. No changes needed..." && sleep 2
         else
-            sed -i "s/numlockx on/numlockx off/g" /etc/lightdm/lightdm.conf && echo "#✔ Disabling Numlock at login..." && sleep .5
+            sed -i "s/numlockx on/numlockx off/g" /etc/lightdm/lightdm.conf && echo "#✔ Disabling Numlock at login..." && sleep 1
         fi
     else
         zenity --info --width="280" --height="60" --timeout=5 --height="60" \
@@ -571,11 +569,14 @@ NUMLOCK() {
     done
 }
 PRELOAD() {
-    echo "#Getting Apps Preload status. Please wait..." && sleep 1 && echo "#Configuring Preload..."
+    echo "#Getting Apps Preload status. Please wait..." && sleep 1
     APPNAME="   Lite Tweaks - Preload Apps"
     SERVICE="preload"
+    LITEAPPSICONS=/usr/share/liteappsicons/litetweaks
+    appicon3=/usr/share/liteappsicons/litesoftware/ll-remove-software_32x32.png
     # the loop
     while (true); do
+    echo "#Configuring Preload..."
     # Is preload installed?
     if [ -z  "$(dpkg -l | grep -E '^ii' | grep preload)" ]; then
         # if not installed, then prompt user for installation
@@ -608,18 +609,21 @@ PRELOAD() {
     fi
     # check if preload service is running and assign variables
     if ps ax | grep -v grep | grep $SERVICE > /dev/null; then
-        val1=TRUE && val2=FALSE && val3=FALSE && status="Running ✔"
-    else val1=FALSE && val2=TRUE && val3=FALSE && status="Stopped ✘"
+        appicon1=$LITEAPPSICONS/appicon1-on.png
+        appicon2=$LITEAPPSICONS/appicon3-off.png
+    else
+        appicon1=$LITEAPPSICONS/appicon1-off.png
+        appicon2=$LITEAPPSICONS/appicon3-on.png
     fi
 
-    # Preload Status Main window
+    # Preload Status Main dialog
     echo "#Configuring Preload..."
-    PRLOAD=$(zenity --width="360" --height=180 --cancel-label="Quit" --ok-label="Change Status" --hide-header --window-icon=$ic --title="   $APPNAME" \
-              --list --radiolist --text "   Preload Status: <b>$status</b>\n\n   Change status:" \
-              --column "Select" --column "Option" --column "Description" \
-              $val1 "Running" "(Preload is currently running)" \
-              $val2 "Stopped" "(Preload is currently stopped )" \
-              $val3 "Remove" "(Remove Preload)")
+    PRLOAD=$(zenity --list --imagelist --width="365" --height=230 --cancel-label="Quit" --ok-label="Change Status" --window-icon=$ic --title="$APPNAME" \
+              --text='                          <span font="Sans Bold 10">Preload Apps Status</span>\n\n    • <span font="Sans 9">Preload service is always started during boot up</span>' \
+              --print-column=2 --column="  " --column="Preload" --column="Description" \
+              $appicon1 "Running" "Preload service is currently running" \
+              $appicon2 "Stopped" "Preload service is currently stopped" \
+              $appicon3 "Remove" "Stop service and Uninstall Preload")
 
     if [ "${PIPESTATUS[0]}" -ne "0" ]; then
         return
@@ -627,7 +631,7 @@ PRELOAD() {
 
     if [[ $PRLOAD =~ Running ]]; then # Start
             if ps ax | grep -v grep | grep $SERVICE > /dev/null; then
-                echo "#Service is already running..." && sleep 1
+                echo "#• Service is already running. No changes needed..." && sleep 2
                 continue
             else
                 echo "#Starting Preload..." && sleep 1
@@ -641,21 +645,26 @@ PRELOAD() {
                 service preload stop
                 echo "#✔ Preload has been stopped" && sleep 1
             else
-                echo "#Service is not running..." && sleep 1
+                echo "#• Service is not running. No changes needed..." && sleep 2
                 continue
             fi
     elif [[ $PRLOAD =~ Remove ]]; then # Remove Preload
-        echo "#Removing Preload. Please wait..."
-        service preload stop && apt-get remove preload -y
-            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-                echo "#Error..." && sleep 1
-                zenity --error --width="260" --height="80" --title="    Error" \
-                       --text="\nAn error occurred while removing Preload!"
-                return
-            else
-                echo "#✔ Preload successfully removed" && sleep 1
-                return
-            fi
+        zenity --question --width="265" --title="$APPNAME" --text="\nAre you sure you want to remove Preload?"
+        if [ "$?" -eq "0" ]; then
+            echo "#Removing Preload. Please wait..."
+            service preload stop && apt-get remove preload -y
+                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                    echo "#Error..." && sleep 1
+                    zenity --error --width="260" --height="80" --title="    Error" \
+                           --text="\nAn error occurred while removing Preload!"
+                    return
+                else
+                    echo "#✔ Preload successfully removed" && sleep 1
+                    return
+                fi
+        fi
+    else
+        zenity  --info --title=" $APPNAME" --text="\nYou did not select an option. Please try again."
     fi
     done
 }
@@ -739,9 +748,9 @@ grep -q "SaveSession=%sudo" $kioskrc && echo $?
             appicon2=$LITEAPPSICONS/appicon2-off.png
     fi
 # main dialog
-answ=$(zenity --list --imagelist --title="$APPNAME" --window-icon="$ic" --width="480" --height="215" \
+answ=$(zenity --list --imagelist --title="$APPNAME" --window-icon="$ic" --width="470" --height="215" \
                 --cancel-label=" Quit" --ok-label=" Apply" --hide-column=2 --print-column=2 \
-                --text='                <span font="Sans Bold 10">Enable or Disable Save Session:</span>\n' \
+                --text='                            <span font="Sans Bold 10">Enable or Disable Save Session:</span>\n' \
         --column=" " --column="ANSW" --column=" Save Session" --column=" Description" \
         $appicon1 "30" "Enable for all users" "Enables Save Session for all users" \
         $appicon2 "20" "Enable for admins" "Enables Save Session for administrators only" \
@@ -752,21 +761,33 @@ if [ "$?" -eq "1" ]; then
 fi
 # prompt when no option is selected
 if [[ $answ -eq "0" ]]; then
-    zenity  --info --window-icon="$ic" --title=" $APPNAME" --text="\nYou did not select an option. Please try again."
+    zenity  --info --title="$APPNAME" --text="\nYou did not select an option. Please try again."
     continue
 fi
 # disables Save Session for all users
 if [[ $answ -eq "10" ]]; then
-    sed -i 's/SaveSession=.*/SaveSession=NONE/' $kioskrc
-    echo '#  Disabling Save Session for all users...' && sleep 1 && echo "#✔ Disabling Save Session for all users..." && sleep .5
+    if grep -q "SaveSession=NONE" $kioskrc; then
+        echo "#• Checking..." && sleep .5 && echo "#• No changes needed..." && sleep 1
+    else
+        sed -i 's/SaveSession=.*/SaveSession=NONE/' $kioskrc
+        echo '#  Disabling Save Session for all users...' && sleep 1 && echo "#✔ Disabling Save Session for all users..." && sleep 1
+    fi
 # enable Save Session for admins only
 elif [[ $answ -eq "20" ]]; then
-    sed -i 's/SaveSession=.*/SaveSession=%sudo/' $kioskrc
-    echo '#  Enabling Save Session for admins only...' && sleep 1 && echo "#✔ Enabling Save Session for admins only..." && sleep .5
+    if grep -q "SaveSession=%sudo" $kioskrc; then
+        echo "#• Checking..." && sleep .5 && echo "#• No changes needed..." && sleep 1
+    else
+        sed -i 's/SaveSession=.*/SaveSession=%sudo/' $kioskrc
+        echo '#  Enabling Save Session for admins only...' && sleep 1 && echo "#✔ Enabling Save Session for admins only..." && sleep 1
+    fi
 # enable Save Session for all users
 elif [[ $answ -eq "30" ]]; then
-    sed -i 's/SaveSession=.*/SaveSession=ALL/' $kioskrc
-    echo '#  Enabling Save Session for all users...' && sleep 1 && echo "#✔ Enabling Save Session for all users..." && sleep .5
+    if grep -q "SaveSession=ALL" $kioskrc; then
+        echo "#• Checking..." && sleep .5 && echo "#• No changes needed..." && sleep 1
+    else
+        sed -i 's/SaveSession=.*/SaveSession=ALL/' $kioskrc
+        echo '#  Enabling Save Session for all users...' && sleep 1 && echo "#✔ Enabling Save Session for all users..." && sleep 1
+    fi
  else
     exit 0
 fi
